version: '3'
services:
  backend:
    build: .
    ports:
      - 9000:9000
    volumes:
      - ./shop:/home/rafalkuzma/ebiznes
    working_dir: /home/rafalkuzma/ebiznes
    command: bash -c "sbt run"
  frontend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./reactapp:/home/rafalkuzma/ebiznes
    working_dir: /home/rafalkuzma/ebiznes
    command: bash -c "npm install && npm start"