# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shopbackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3b275d11cbe6464ca835017567748e42 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cdadbb46514544c29eca2a57c7e87386 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3b275d11cbe6464ca835017567748e42 }}/ebiznesbacked:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shopbackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3bdf868b44034b09a1903342f971c66c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3b275d11cbe6464ca835017567748e42 }}/rafalkuzma1/ebiznesbacked:${{ github.sha }}'