# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shopfrontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b7c805385b2a41a28a206df2eef48ff2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_59567d93a09241aeaa7c93f74cd766a1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b7c805385b2a41a28a206df2eef48ff2 }}/ebiznesfrontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shopfrontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d83eb6422a324536873bcf2ab17d63b9 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b7c805385b2a41a28a206df2eef48ff2 }}/ebiznesfrontend:${{ github.sha }}'